#!/usr/bin/env python

import sys
import numpy as np
import matplotlib.pyplot as plt

filename = sys.argv[1:]

plt.rcParams['legend.loc'] = 'best'
plt.rc('font', family='serif')
fig, ax =  plt.subplots()
xy = [None]*len(filename)
for i, files in enumerate(filename):
    if files.split(".")[-1] == "npy":
        xy[i] = np.load(files)
    else:
        xy[i] = np.loadtxt(files)
    if xy[i].shape[1] == 2:
        ax.plot(xy[i][:,0], xy[i][:,1], '-', label=files)
    elif xy[i].shape[1] > 2:
        ax.errorbar(xy[i][:,0], xy[i][:,1], xerr=xy[i][:,2], label=files) 
ax.legend()
ax.grid(True)
plt.show()
